### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-wordpress-api#1]
I see it's not a standard Wordpress plugin. 
1) Why not?
2) So how to install this code?

Is some cron script required to update the administrative database regularly?

How to login into the admin panel? Using your Wordpress admin account?

Please create `INSTALL.md` file explaining all this.

**Comment by catalintenita** [comment]
Hi Krzysztof,

We decided to split the project in two distinct modules: one importer that takes the necessary data from the WP tables and put it into a distinct set tables (adding some other info like keywords, stats etc) and one module for the API server.
There are two main reasons for this decision:
1. Budget/work-hours. Given the fact we had to deliver everything in 40 hours of work the option of a WP plugin wasn't financially efficient enough.
2. Flexibility. We think this kind of approach allows some distinct fact-checking teams to use the code, no matter if their fact repository is based in Wordpress or not.

Q2: You just drop the files, and change the connect/server parameters.

Q3(cron script: No, there is no cron script, because the fact entering activity is not continuos. There is an "Update" button in the backend interface.
Q4(admin) panel:  Admin interface http://www.factual.ro/api/administrative (I'll provide you with the user/pass by email)

Thx,
Catalin

**Comment by KrzysztofMadejski** [comment]
Shouldn't it be automatic - if somebody adds a factcheck it's automatically imported in the admin? This could be resolved by cron.. And then some extra info can be added via admin panel.. CC: @yozness 

Q2: Should the files be dropped in the main WP folder? (where wp-config resides)

**Comment by catalintenita** [comment]
We can add a cron job, but I don't think it's okay to run a process every minute or so when the fact-checks are added in batches probably 10-20 at most once every 1-2 weeks.

Q2: We set different folders in order to be moved on other servers if needed.

**Comment by KrzysztofMadejski** [comment]
Q2: Let's talk it over skype.

**Comment by KrzysztofMadejski** [comment]
- [ ] Written documentation needed

**Comment by catalintenita** [comment]
Solved, in the README.txt file (description, installation, extending/changing of the scripts, documentation of the files and API method)

**Comment by KrzysztofMadejski** [comment]
How this administration panel connects with Wordpress site? Should `$cfg_db_array['db_user'] = "";` point to the wordpress mysql instance? Should `$cfg_db_array['db_wp'] = "";` point to the wordpress db name?

Apart from that it's clear for me.

**Comment by catalintenita** [comment]
Answers:
$cfg_db_array['db_database'] points to administrative panel database
$cfg_db_array['db_wp'] points to wordpress database
$cfg_db_array['db_user'], $cfg_db_array['db_passwd'] and  $cfg_db_array['db_host'] are server connect parameters
We added this explanation to the installation readme.txt

**Comment by KrzysztofMadejski** [comment]
Ok!

I've just moved steps around and specified that administrative database has to be on the same server as Wordpress: https://github.com/TransparenCEE/factchecker-wordpress-api/commit/dcda06006a2ce041455a9512e441e106953544b1
